### ISSUE TITLE
Initial Config

### ISSUE THREAD

**Issue by Cbuijse** [Lawmate/BQ4050#8]
Hello,

Does this library assume that you do the initial config using BQstudio from TI or will it work without it?

**Comment by Lawmate** [comment]
Hi, you should be able to use it without BQStudio and the EV2400. I have only used it with a Teensy though, so you may need to adapt it if using a different board. If your circuit is correct, you should be able to communicate with the device as it is from factory. The first setting to change is the number of cells, then you should be able to read most values.
You can implement a sweep of all the registers like in BQStudio or just get individual values. There is a lot of set up if you want the device to run well over a long period though. You need to run learning cycles. This is a function built into BQStudio. You could definitely write your own, but without the learning cycle data, you won't get the correct offset values to display percentage of bat remaining.
The library is designed for use alongside BQStudio really. It 'could' be used standalone, but the complexity of the BQ4050 means some of the BQStudio features are necessary and you'd have to roll your own to get around it.

**Comment by Cbuijse** [comment]
Hello,

Thanks for the reply.
It is a proof concept so spending 200$ on a EV2400 is quite steep.

As long as i can read the cell voltages and do some basic balancing it should be okay.

**Comment by Lawmate** [comment]
Yeah, you should be able to read values. Make sure you set the correct number or cells, else you won't be able to read them. If you're using Lion, that's the only setting you really need to set. I believe it is defaulted to 3 cells. I found the balancing is very gentle too. If one battery is vastly out of balance, it will take quite a number of charging cycles before that cell is balanced.
As I understand, no charging occurs when any single cell has reached it's full charge voltage. Prior to that, whilst charging is in progress, the balancing algorithm just bleeds off a small amount of current from the individual cells that are at a higher voltage than the others.
You'll have to get familiar with the operation manual. Also the e2e forums are really helpful if you have any questions, and there are a load of posts about the BQ4050.

**Comment by Cbuijse** [comment]
Alright thats good to know ill see if i can get it to work.

Thanks for the quick replies.

I'll close the issue now.
